import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/registry";
import NaviComponent from "@/components/NaviBox";
import { Roboto } from "next/font/google"; // 해당 폰트의 함수를 사용합니다.

export const metadata: Metadata = {
  title: "SOOHO's HoMEPaGE",
  description: "Generated by create next app",
};
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <NaviComponent />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
